// Real portfolio content — Silveira Software
const PROJECTS = [
  { icon: "💳", n: "01", title: "CremePay Gateway", sub: "Gateway de Pagamentos", desc: "Gateway completo de intermediação financeira com PIX instantâneo, cartões, boletos, dashboard, antifraude e até 98% de aprovação.", tags: ["PHP","Node.js","MySQL","API REST","Antifraude"], cat: "Fintech", url: "https://cremepay.com/" },
  { icon: "🔗", n: "02", title: "CremePay API", sub: "API de Pagamentos", desc: "API robusta para integração de pagamentos com documentação completa, webhooks e suporte técnico dedicado.", tags: ["PHP","Node.js","MySQL","REST API","Webhooks"], cat: "Fintech", url: "https://api.cremepay.com/" },
  { icon: "💰", n: "03", title: "PinaCash", sub: "Sistema Financeiro", desc: "Plataforma financeira completa com gestão de transações, cashback, carteira digital e relatórios avançados em tempo real.", tags: ["PHP","Node.js","MySQL","API","Dashboard"], cat: "Fintech", url: "#" },
  { icon: "🧾", n: "04", title: "Checkout Pro", sub: "Checkout Transparente", desc: "Sistema de checkout otimizado para conversão com split de pagamento, upsell, order bump e recuperação de carrinho abandonado.", tags: ["React","Node.js","PIX","Cartão","Boleto"], cat: "Fintech", url: "#" },
  { icon: "🎰", n: "05", title: "PG Sorte Bet", sub: "Apostas Esportivas", desc: "Plataforma completa de apostas esportivas white-label com odds em tempo real, cashout, bônus e interface moderna.", tags: ["PHP","MySQL","JavaScript","WebSocket","API"], cat: "Games", url: "https://bet.pgsorte.shop/" },
  { icon: "🎲", n: "06", title: "China Bet", sub: "Plataforma iGaming", desc: "Plataforma de jogos e apostas com design moderno, sistema de pagamentos integrado e marco regulatório brasileiro.", tags: ["PHP","MySQL","JavaScript","API","KYC"], cat: "Games", url: "https://chinabet.pgsorte.shop/" },
  { icon: "🕹️", n: "07", title: "Retro Games", sub: "Games de Habilidade", desc: "Plataforma de jogos retrô de habilidade com ranking, torneios e possibilidade de ganho em dinheiro real.", tags: ["JavaScript","Canvas","PHP","MySQL"], cat: "Games", url: "https://retrogames.pgsorte.shop/" },
  { icon: "⚙️", n: "08", title: "N8N Automações", sub: "Automação de Workflows", desc: "Plataforma self-hosted de automação de workflows inteligentes com integração a centenas de APIs e serviços.", tags: ["N8N","Node.js","Docker","API REST"], cat: "Automação", url: "https://n8n.liberar.site/" },
  { icon: "📡", n: "09", title: "FunilQIC Tracking", sub: "Rastreamento Avançado", desc: "Ferramenta própria de rastreamento avançado com Server-Side Tracking, eventos customizados e APIs de Conversão Meta/TikTok.", tags: ["Tracking","Server-Side","Meta API","TikTok API"], cat: "Automação", url: "#" },
  { icon: "🧲", n: "10", title: "Lead-Machine", sub: "Geração de Leads", desc: "Sistema completo de captura, qualificação e nutrição de leads com funis automatizados, scoring e integração com CRMs.", tags: ["PHP","Node.js","N8N","API","CRM"], cat: "Automação", url: "#" },
  { icon: "💬", n: "11", title: "WhatsApp Dispatcher", sub: "Disparos em Massa", desc: "Sistema avançado de disparos em massa via WhatsApp com segmentação, templates, agendamento, relatórios e API de integração.", tags: ["Node.js","WhatsApp API","MySQL","WebSocket"], cat: "Disparos", url: "https://whatsapp.encxr.shop/" },
  { icon: "📱", n: "12", title: "SMS Dispatcher", sub: "Disparos SMS em Massa", desc: "Plataforma de envio de SMS em massa para campanhas de marketing, notificações transacionais e alertas de segurança.", tags: ["PHP","MySQL","API SMS","JavaScript"], cat: "Disparos", url: "https://sms.cremepay.com/" },
  { icon: "📧", n: "13", title: "Email Dispatcher", sub: "Email Marketing & Transacional", desc: "Sistema de disparos de e-mail em massa com templates HTML, segmentação de listas, automação de campanhas e rastreamento de aberturas/cliques.", tags: ["PHP","SMTP","MySQL","HTML","API"], cat: "Disparos", url: "#" },
  { icon: "🛡️", n: "14", title: "KYC System", sub: "Verificação de Identidade", desc: "Sistema completo de Know Your Customer com validação de documentos, selfie match, consulta CPF/CNPJ, antifraude e compliance regulatório.", tags: ["PHP","Node.js","OCR","API","Compliance"], cat: "Segurança", url: "#" },
  { icon: "🔮", n: "15", title: "Obsidian", sub: "Painel de Segurança", desc: "Dashboard de segurança e monitoramento com detecção de fraude em tempo real, logs de acesso, alertas e gestão de risco.", tags: ["React","Node.js","WebSocket","Redis","AI"], cat: "Segurança", url: "#" },
  { icon: "📺", n: "16", title: "IPTV Streaming", sub: "Streaming Platform", desc: "Plataforma completa de streaming IPTV com mais de 10.000 canais, filmes e séries em HD/4K com CDN próprio.", tags: ["PHP","MySQL","HLS","CDN"], cat: "Streaming", url: "https://iptv.liberar.site/" },
  { icon: "🌿", n: "17", title: "NatLiving E-commerce", sub: "Loja Virtual", desc: "Loja virtual de produtos naturais com carrinho, pagamento PIX, gestão completa e automações de operação.", tags: ["WooCommerce","PHP","MySQL","PIX"], cat: "E-commerce", url: "https://natliving.liberar.site/" },
  { icon: "🎄", n: "18", title: "Império Natalino", sub: "E-commerce Sazonal", desc: "E-commerce de decorações natalinas com frete grátis, desconto no PIX e gestão de estoque sazonal.", tags: ["WooCommerce","PHP","MySQL","PIX"], cat: "E-commerce", url: "https://woodemo1.liberar.site/" },
  { icon: "🛍️", n: "19", title: "HTMLtoShopify", sub: "Migração Shopify", desc: "Ferramenta de conversão e migração de sites HTML estáticos para temas Shopify com preservação de layout e SEO.", tags: ["Shopify","Liquid","HTML","CSS","JavaScript"], cat: "E-commerce", url: "https://github.com/Silveira-Software/HTMLtoshopify" },
  { icon: "🤖", n: "20", title: "Pixel Agents", sub: "Escritório Virtual com IA", desc: "Escritório virtual com agentes de IA integrados para produtividade, automação de tarefas e colaboração inteligente.", tags: ["AI","React","Node.js","WebSocket"], cat: "IA & Tools", url: "https://github.com/Silveira-Software/pixel-agents" },
  { icon: "✨", n: "21", title: "Prompts Engine", sub: "Gerenciador de Prompts IA", desc: "Sistema de criação, organização e otimização de prompts para modelos de IA com templates, variáveis e versionamento.", tags: ["AI","GPT","React","Node.js","MongoDB"], cat: "IA & Tools", url: "#" },
  { icon: "🏘️", n: "22", title: "RepoTown", sub: "Open Source", desc: "Plataforma open-source para gerenciamento, visualização e análise de repositórios Git.", tags: ["Open Source","GitHub","Node.js","React"], cat: "IA & Tools", url: "https://github.com/Silveira-Software/RepoTown" },
  { icon: "🏢", n: "23", title: "Brokers Ribeiro e Dias", sub: "Sistema Imobiliário", desc: "Sistema completo de imobiliária com busca inteligente, filtros avançados, listagem de imóveis e contato via WhatsApp.", tags: ["PHP","MySQL","JavaScript","Bootstrap"], cat: "Sistema", url: "https://diaseribeiro.com/" },
  { icon: "🤝", n: "24", title: "BotMentoria", sub: "Bot de Atendimento", desc: "Bot inteligente para mentorias e atendimento automatizado com fluxos conversacionais e integração com WhatsApp/Telegram.", tags: ["Node.js","AI","WhatsApp","Telegram","MySQL"], cat: "IA & Tools", url: "#" },
];

const SERVICES = [
  { icon: "⚙️", title: "Automação N8N", desc: "Automatize processos, integre sistemas e crie workflows inteligentes que trabalham 24/7 para seu negócio." },
  { icon: "💳", title: "Gateway de Pagamento", desc: "Integração completa com PIX, cartões e boletos. Taxas competitivas e até 98% de aprovação." },
  { icon: "🖥️", title: "Sistemas Web & SaaS", desc: "Desenvolvimento de sistemas completos, painéis administrativos, CRMs e ERPs personalizados." },
  { icon: "📺", title: "Streaming & IPTV", desc: "Plataformas de streaming completas com milhares de canais, filmes e séries em HD/4K." },
  { icon: "🛒", title: "E-commerce", desc: "Lojas virtuais completas com carrinho, pagamento integrado, gestão de produtos e estoque." },
  { icon: "💬", title: "WhatsApp & SMS", desc: "Sistemas de automação, envio em massa e integração com WhatsApp Business API e SMS." },
  { icon: "🔗", title: "APIs & Integrações", desc: "Desenvolvimento de APIs RESTful robustas, WebSockets e integrações com sistemas externos." },
  { icon: "🎰", title: "Games & iGaming", desc: "Plataformas de jogos, apostas esportivas e entretenimento digital com marco regulatório." },
  { icon: "📡", title: "Server-Side Tracking", desc: "Rastreamento avançado com APIs de Conversão Meta/TikTok e análise de tráfego." },
  { icon: "☁️", title: "Infra AWS & DevOps", desc: "Arquitetura cloud com EC2, S3, RDS, Docker e Linux Server com escalabilidade real." },
  { icon: "🤖", title: "Inteligência Artificial", desc: "Escritórios virtuais com agentes de IA, automação inteligente e soluções de produtividade." },
  { icon: "🌐", title: "Sites Institucionais", desc: "Sites modernos para barbearias, tabacarias, pizzarias, mecânicas e outros negócios locais." },
];

const CLIENTS = [
  { name: "Emporium Adega & Tabacaria", cat: "Tabacaria", url: "https://web-emporium-adega-e-tabacaria.vercel.app" },
  { name: "Point Ah Fonte", cat: "Estabelecimento", url: "https://web-point-ah-fonte.vercel.app" },
  { name: "Barbearia Carvão", cat: "Barbearia", url: "https://web-barbearia-carv-o.vercel.app" },
  { name: "Barbearia do João", cat: "Barbearia", url: "https://web-barbearia-do-jo-o.vercel.app" },
  { name: "Hookah Premium Lounge Bar", cat: "Tabacaria & Lounge", url: "https://web-hookah-premium-tabacaria-lounge-silveirasoftwares-projects.vercel.app" },
  { name: "Oxford Barber", cat: "Barbearia", url: "https://web-oxford-barber-silveirasoftwares-projects.vercel.app" },
  { name: "Auto Mecânica Corujão", cat: "Mecânica", url: "https://web-auto-mec-nica-coruj-o.vercel.app" },
  { name: "Tabacaria Lee", cat: "Tabacaria", url: "https://web-tabacaria-lee.vercel.app" },
  { name: "Barbearia Lima", cat: "Barbearia", url: "https://web-barbearia-lima.vercel.app" },
  { name: "Pizzaria Sabores da Villa", cat: "Pizzaria", url: "https://web-pizzaria-sabores-da-villa.vercel.app" },
  { name: "Borracharia Cosmes", cat: "Borracharia", url: "https://borracharia-cosmes.vercel.app" },
  { name: "CompNeus", cat: "Automotivo", url: "https://compneus.vercel.app" },
];
